#!/usr/bin/env bash

if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Usage: ${0##*/} <repo-url> <open-in-editor-command> [path]"
  exit 1
fi

if [ -z "$3" ]; then
  path="$(echo "$1" | sed 's#.*/##;s/\.git$//')"
else
  path="$3"
fi

if [ -d "$path" ]; then
  echo "Path $path already exists!"
  echo "Please remove it or choose a different path."
  exit 1
fi

echo "Cloning $1 into $path"
git clone --recurse-submodules $1 $path

printf "\nOpening %s in %s...\nPress ENTER to continue:\n" "$path" "$2"
read

$2 $path
